---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64
    
steps:
- name: run terraform
  image: jmccann/drone-terraform:latest
  settings:
    actions:
      - validate
      - plan
